name: dendrite-monolith
image: ubuntu-20-04-x64
min_size: 1gb
config:
  packages:
    - git
    - golang
  runcmd:
    - touch test.txt
    - echo "hi" > test.txt
    - echo "go --version" > go.txt
    - git clone https://github.com/matrix-org/dendrite
    - cd dendrite
    - go build -o bin/dendrite-monolith-server ./cmd/dendrite-monolith-server
    - go build -o bin/generate-keys ./cmd/generate-keys
    - ./bin/generate-keys --private-key matrix_key.pem --tls-cert server.crt --tls-key server.key