name: dendrite-monolith
image: ubuntu-20-04-x64
min_size: 1gb
config:
  packages:
    - git
    - golang
    - docker
  runcmd:
    - touch test.txt
    - echo "hi" > test.txt
    - echo "go --version" > go.txt
    - echo "docker version" > docker.txt
    - git clone https://github.com/matrix-org/dendrite
    - cd dendrite
    # - go run github.com/matrix-org/dendrite/cmd/generate-keys \
    # - --private-key=matrix_key.pem \
    # - --tls-cert=server.crt \
    # - --tls-key=server.key