name: dendrite-monolith
image: ubuntu-20-04-x64
min_size: 1gb
config:
  packages:
    - git
    - golang
  runcmd:
    - cd ~
    - git clone https://github.com/matrix-org/dendrite
    - echo "hey there" > test.txt
    - cd dendrite
    - go build -o bin/dendrite-monolith-server ./cmd/dendrite-monolith-server
    - go build -o bin/generate-keys ./cmd/generate-keys