name: dendrite-monolith
image: debian-9-x64
min_size: 1gb
config:
  packages:
    - wget
  runcmd:
    - wget https://raw.githubusercontent.com/annie-elequin/dendrite/master/installmonolith.sh
    - bash installmonolith.sh